language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-dom
    all_branches: true
  api_key:
    secure: LCquNieTsRgx8uIcWzIpjllkuU6u81tICwYPaniB7UVlaFGquDhFKQxKlVOYOyKofdosw1K8BA2BEIKtybRR3DQo8NcMJKy3+yM3wPlz6/m+vU6ecrPLfiy3BHsnyHQ45FXh2LO1kayVBlNS33eOFQaXMKg6Cmf2t2g3nygKmd04OtnxAjH/q4/z5lkNBVQctiTc4uVLzyB/3G/FMz+Cik9NcH0eJq310UnW7y9f0f5PsFZCsGQNQbxPjx1xzlv/1+CjtX5ohUIQkC3ZhUT2LxIc05238imJ+LMx1KYda38/NSnxEw+RpmnNbETP9yRQgC5MuohSk3PlknN96i683HaPsWl5xcKlhyAkfuQSOm7DaTZX6VgEyYwXlrxKOd9zZYp2L/6Xj7PRiDPAuFKA8oMBQg1kugHVFI7rOm+6i/zs9vFP14fW0VY+6XjMuEjQYrVLSgLtHVYwHTtpGOgZEVo0DZDvTloe9TUyotg+feS+QKxJu34wYYuRt/qb49uipqIBfGpEW/4hZAOog5NEwPygaUc6kMAXNZwDs6Qbksmm0Ar2KAiUm1AkQtsVWOYosPzc1sWQVurE49zc7DjL1918G3QlerWDRw8kAmURjiaDw50UXe4aFAHKmO+BwuYq+2dozEs+UDMgY5He3007dV1siCZLlVonSu3gB3ZXlPc=
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
