language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-dom
    all_branches: true
  api_key:
    secure: FTSpc0rds6SulOBFjlZSGkFgHUCMk7jAgr+8vQFJhx4LxZ0ONG25ANX/7DyCBnbHk371AaX1dZO2x+vauk+HrL5Y39oNB25zrnoMkXBl9KNkXsb/AWYdj+jxr5/PBWpK3grDV10JhixS4bpddCiNgb0Qw0dh+priADBnrPScoDGTAAJRC+6YKS9Fzeqz5Ao3Q4uPC9WgdcD+iqZfFxUuVoEJpa4JrYTf+EikuE9MOneHWd9Ex3fJT3CEmA4Quy/LSgNOhC5NHyoJemi4SNiCxxAHdR/c/Y+ZTxPOAR03GytUgAt1KT3MYGYQshG3udazMKN9p3MLzrFrLPLwZx8UGzh6VWFPLFI/vOk/8UXn5496dwtBJUdamWskbm3x6mRekCAkZsBXy09iHLhOzWK6z/cCCkwcJ1Kzz6N4KGe4RgAqguAIhIeq9m8luufsHUReulQzCA8S62qr3FdLT5cHZ9T23UU+Kq1XAZxdZs7FhtfNe4goEXG6Ho+xPn94mBC2OEQvIrJxaWf6cbrWryNqswzbRLWvOlhpVS4MCVCzgFUCHXLT0eQsTU0tFk+j/fSKyNZ03ROzWTOMPUd3Hcn1mG4QOp54HNWNyHHn4wdpwi71oV0ET1TFUfMzTPsrC3zYspTCL0Be4/cDvCekQF89gTFp/NsrgXkfXWASorR2qLI=
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
