language: node_js
node_js: '10'

install:
  - npm i --no-save @lampix/core
  - npm ci

deploy:
  provider: npm
  email: dbalaban@lampix.co
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-dom
    all_branches: true
  api_key:
    secure: YJDAavpni6wGEPq78DTJS9Vp8vA2qkzuCCNOiCEkkvhdYmZx/v4nQpwK5agZvBZdWPTxMsVkV3yeBTs1Y0fCZFQ4fFwwoMBpe9Ih6FFN6DKCUlB7TEfSmFtU27YzDsgVjhedn/f6CswoSVsZOKXN9mY87QgS1T8ogr8OOm/agFVz+GZbH1LZqPYLIqpJVYRk1fWO+1zbhJQXzgbNuWpNilnTsRtUUE3qqJG1mEV68A+FbXB//GZ4//yVBvazBxO+/hP+qr+upNorjr/t6mcxqUFNO0sHxH23veWYwTb4qgcWxdPTx+qqHGJhjhHleMaVcYsj5Xb/l8oWc0n8TWWmE9kNlvf/Y0u8Q64A2VmOtkZPZOzfA8I7pvkjwNyV+8h18RIQv9IlxbFclPV7kjPh7VFj2jzLnE9d977rjTKhCUcf3qhOsc08pUBVcCDSgHL0VEEoz1/iyq2Em2ZugDIQww2WnNtpYSdfI5NO0iixD5u85HydWks2ya1H7oqkxP/+SulvqLYlUQXEIAbqANyoAQh964cGZlSpp9jTdNtTmCPQt5UeFe8DmouT7jDM2rth7FxunBu3cWsPucUn5d10i6Gtb6BNLaQTfIdcadq4vGhRtafc52ZFqW1daQioqlDyN0he0HGeChg7nQqpLNQr8QS2Yy+L7I+iZHt5mQTZJds=
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
