language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-dom
    all_branches: true
  api_key:
    secure: b8lEcUB5PhzrVNyeQqamjgjbffMF+Jdav/04XshdWnY4rlq1NhHj81Qfbub7GFzK3uzqGur4oewhS3zdITsbpwZO0bNrdrsx4Tm2mLfqwCeqyUaiLkcPO3NfdsuURbTJS0L05Bn1On21GHvctmm99gd5B883oq+1LhhuRkCHS6Oz7rSRpHHOa6k0+yUAvrmyIwgoK9vNcpgdkvRufaiCNrq4b4IoUfZxuMtyJUfY4b3zgfr2apb62iQ16o8p4VuEX1C6RvscdXLqQRO/p6rUZqcgVHOF0N5lN5wRqKKeBEnq5vllrjyP5xVk9RqE2h+gWr2kXs5fJc0AhQy8cf8NIWH/B9QHU1LTwbUpJUS8bjwWPWsMs7qkKdm9FUQZkbtGjBFVtKkNNjPSv11kayGXp44ccV8+fsVG6I4imsBjNrl4d9BXmtDh/ESHXO8Dc2BUIGUybX5rHRbe3KNP8jtRwhXQy53g69J99Vs3K/nZCR4AfGaRmRUUknvcrc1w9ahZfU28bm9+VY+yRZj0Kr9wOrXvAZ6owEmDvg3uj6qSqbYYxSrWb4nrU8n5NbcbQW6WWjPMu2xCSevO3yoFEEAJ1u/ObdMFASQ7Z7FwP+jXwVRrOL1mBqHd1BNATjxtnt81Nuj3laPHp8j0po+bmPKb7AVcc977xskUz3FKHQg2NOg=
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
